name = "GaussletBases"
uuid = "5d4de616-c9ab-4678-9ab9-e835b9559837"
version = "0.1.0"
authors = ["Steven R. White"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10"
